name: Full Stack CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  front-end-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: Install root dependencies
        run: npm install
      - name: Install client dependencies
        run: cd client && npm install
      - name: Run Cypress tests
        run: npm run cypress:run

  back-end-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: Install server dependencies
        run: |
          cd server
          npm ci
      - name: Install client dependencies
        run: |
          cd client
          npm ci
      - name: Run tests (Jest/SuperTest)
        run: |
          cd server
          npm test
