name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Set this to the node version you are using

    - name: Install dependencies
      run: cd client && npm install

    - name: Build
      run: cd client && npm run build  # If you have a build script

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12  # This is a community action for deploying to Heroku
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "radiant-falls-95660"  # Set this to your Heroku app's name
        heroku_email: "taein.um@stonybrook.edu"  # Set this to the email associated with your Heroku account
