name: Front-End CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: JuyeeMyeong/checkout@v2
    
    - name: Set up Node.js
      uses: JuyeeMyeong/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install root dependencies
      run: npm install

    - name: Install client dependencies
      run: cd client && npm install
      
    - name: Run Cypress tests #with deployed address
      run: npm run cypress:run      
