name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install root dependencies
      run: npm ci

    - name: Install client dependencies
      run: |
        cd client
        npm ci

    - name: Run Cypress tests
      run: |
        cd client
        npm run cypress:run
