name: Back-End CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@3
        with:
          node-version: "20.x"

      - name: Install server dependencies
        run: |
          cd server # go to server dir
          npm ci

      - name: Install client dependencies
        run: |
          cd client # go to client dir
          npm ci
      - name: Run tests (Jest/SuperTest)
        run: |
          cd server # go to server dir
          npm test
