name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x' # 또는 원하는 노드 버전

    - name: Install dependencies
      run: |
        cd server # 서버 디렉토리로 이동
        npm ci

    - name: Run tests
      run: |
        cd server # 서버 디렉토리로 이동
        npm test

    - name: Run front-end tests
      run: npm run cypress:run
